# Project
seed: 2025
work_dir: workdir/hipmri_vqvae


# Data
data_root: data_hipmri_2d # imagesTr/*.nii.gz
images_dir: imagesTr
img_size: [128, 128]
batch_size: 64
num_workers: 6


# Model (VQ‑VAE only)
hidden: 128
z_channels: 64
n_res_blocks: 2
codebook_size: 512
commit_beta: 0.25
ema_decay: 0.99


# Optim & Train
epochs: 80
lr: 0.0002
early_stop_patience: 15
mixed_precision: true